### ISSUE TITLE
Massive performance issues

### ISSUE THREAD

**Issue by Antafes** [xkodyhuskyx/CompleteMobControl2#1]
With Minecraft 1.13 using Craftbukkit 1.13 there are massive performance issues while using CMC2.
My server already tells me, it can't keep up right after starting it.
I've attached the whole log of my latest attempt at running it: [latest.log](https://github.com/xkodyhuskyx/CompleteMobControl2/files/2276001/latest.log)

As you can see, I've only installed CMC2 and nothing else. Although it's saying that I used v2.00 B3, it's actually the latest [snapshot from 15.07.2018 00:52](https://ci.kodyhusky.com/job/CompleteMobControl2/1/).

And no, my server isn't lacking power. After disabeling CMC2 it runs perfectly fine.

If you need more information, please tell me and I'm happy to get them.

**Comment by xkodyhuskyx** [comment]
Hey @Antafes,

With the release of Minecraft 1.13 there were many changes in the way craftbukkit implements plugins dealing with world and entity management. CMC2 currently doesen't support 1.13 although I am actively working towards the release of a beta 1.13 version. The version currently on my CI server only has minor changes to work with 1.12.2.

I will make sure to keep you posted on the upcoming release of the 1.13 version of the plugin.

**Comment by Antafes** [comment]
Thanks for the heads up information. I'll gladly test the beta version, as I really like the concept of CMC :)

**Comment by xkodyhuskyx** [comment]
Just posted a development build with partial 1.13 support although some features such as ForceFields and the ability for repellers to kill mobs when they cross borders are still unavailable and have been disabled. Also, please note it may be a bit unstable, it has not been thoroughly tested.
https://github.com/xkodyhuskyx/CompleteMobControl2/releases/tag/1.13

**Comment by Antafes** [comment]
Hi @xkodyhuskyx,
the performance issues are gone so far and the repellers prevent spawning of any mob at all, even the neutrals.

**Comment by xkodyhuskyx** [comment]
Hey @Antafes,
I had accidentally used an incorrect function when checking for neutral entity type names. I have posted a new build here that should correct the issue with neutrals always being repelled.
https://ci.kodyhusky.com/job/CompleteMobControl2/6/

**Comment by Antafes** [comment]
Spawning is working correctly now. Going to test it a bit further to see if there are any other problems.

**Comment by Antafes** [comment]
I'm getting the following error while crafting on my server:
> Could not pass event PrepareItemCraftEvent to CompleteMobControl v2.1.0 D1
> org.bukkit.event.EventException: null
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:775) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.Container.a(Container.java:642) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.ContainerWorkbench.a(ContainerWorkbench.java:54) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.InventoryCrafting.splitStack(InventoryCrafting.java:130) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.SlotResult.a(SourceFile:63) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.ContainerWorkbench.shiftClick(ContainerWorkbench.java:119) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.Container.a(Container.java:249) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2070) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
>     at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:827) [craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:376) [craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:780) [craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:683) [craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
>     Caused by: java.lang.NullPointerException
>     at com.kodyhusky.cmc.EntitySpawnListener.onCraft(EntitySpawnListener.java:49) ~[?:?]
>     at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
>     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
>     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.13.jar:git-Bukkit-4a24108]
>     ... 22 more

**Comment by xkodyhuskyx** [comment]
I have created a workaround for the crafting issue and have released a new development build here:
https://ci.kodyhusky.com/job/CompleteMobControl2/7/

I have also added a few changes in the build to fix the lag issue with listeners. If you are willing, could you remove the devcode: "nolisten" from your plugin configuration and see if you still experience any massive lag issues?

**Comment by Antafes** [comment]
The crafting issue is gone and I only got one lag warning right at the beginning of the server start. I'll leave it without nolisten for the time being and see if there will be any further problems.

**Comment by Antafes** [comment]
The performance issue continues to persist, but only if more than 1 player is on the server.
In addition I got the following exception today:
> [CompleteMobControl] Plugin CompleteMobControl v2.1.0 D1 generated an exception while executing task 10
> java.util.ConcurrentModificationException: null
>         at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_181]
>         at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_181]
>         at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getLivingEntities(CraftWorld.java:624) ~[craftbukkit-1.13.jar:git-Bukkit-bfb9131]
>         at com.kodyhusky.cmc.FFieldMoveListener.run(FFieldMoveListener.java:24) ~[?:?]
>         at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit-1.13.jar:git-Bukkit-bfb9131]
>         at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.13.jar:git-Bukkit-bfb9131]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by xkodyhuskyx** [comment]
Hey Antafes,

I am looking into what is causing the issues and will let you know as soon as I can find another potential solution.

**Comment by xkodyhuskyx** [comment]
I have just released a new development version here: https://ci.kodyhusky.com/job/CompleteMobControl2/8/
There were numerous issues I was unable to work around with forcefields, they have been removed in this version but will be returning in CMC v3.

**Comment by Antafes** [comment]
Hi kody,
performance is looking fine so far. I'll be checking for a few days and if no further problems occur, I'll close this issue.

**Comment by xkodyhuskyx** [comment]
Alright, also if you are interested in beta testing the 3.0.0 version please shoot me an email at xkodyhuskyx@gmail.com and i'll be in touch.

**Comment by xkodyhuskyx** [comment]
Marking this issue as closed, the issue appears to be resolved and no responses have been left for quite a while.
